### ISSUE TITLE
Plugin should wait until the /crx/packmgr is up

### ISSUE THREAD

**Issue by trekawek** [wttech/Maven-CRX-Plugin#10]
Sometimes it happens that we upload and install a few packages, one after another. If a package contains bundles extending the core AEM features (eg. login-module), the CQ restarts a lot of internal bundles, including the one responsible for `/crx/packmgr` servlet. If we try to install another package when the servlet is inactive, the request will be handled by Sling POST servlet and it'll create a new node in the repository (/crx/packmgr/...) rather than installing the package.

Maven plugin should ping the `/crx/packmgr` servlet before invoking an action and wait until it works. If it doesn't turn on in eg. 30 seconds, the build should fail, without POSTing anything.

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
