### ISSUE TITLE
Pickup SAXException as error

### ISSUE THREAD

**Issue by ByteFader** [wttech/Maven-CRX-Plugin#13]
If there is an error while importing content because of a nullpointer sax exception then the build fails but the error is not parsed from html.

Error pattern in the HtmlParser should be updated to pick it up

``` java
private final Pattern errorPattern = Pattern.compile("<span class=\"E\"><b>E</b>&nbsp;(.+\\s??.+)</span>");
```

testcase to pickup

``` html
"<span class=\"E\"><b>E</b>&nbsp;/content (org.xml.sax.SAXException\n" +
                "java.lang.NullPointerException)</span><br>\n"
```

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
